### ISSUE TITLE
vulners.statistics:vulners.scoreMax receives float values

### ISSUE THREAD

**Issue by yerkanian** [vulnersCom/zabbix-threat-control#10]
The following got logged in /var/log/zabbix/zabbix_server.log:
```
item "vulners.statistics:vulners.scoreMax" became not supported: Value "7.5" of type "string" is not suitable for value type "Numeric (unsigned)"
```

The item also became "Not supported" in the Zabbix UI and the Hosts/Packages/Bulletins blocks are empty.

**Comment by samosvat** [comment]
To fix the created ZTC instance:

- Select the "**Vulners - Statistics**" host  and change item "**CVSS Score - Maximum**":  
- Set **Type of information** to **Numeric (float)**:

<img width="798" alt="image" src="https://user-images.githubusercontent.com/14240138/43185198-dd21ec6a-8ff3-11e8-8ab5-269be67fcb36.png">
