### ISSUE TITLE
any server exclude from scan

### ISSUE THREAD

**Issue by adziubin** [vulnersCom/zabbix-threat-control#14]
on every server when I run ztc.py script can't find any software on any server

INFO  Excluded Atlassian.  ~^S: 0, Version: 0, Packages: 1  [ztc.py:83]                                          │
INFO  Excluded Zabbix Server.  ~^S: 0, Version: 0, Packages: 1  [ztc.py:83]

**Comment by samosvat** [comment]
Hi!

- Check permissions on `/opt/monitoring/os-report/report.py` Zabbix user must be able to run it on every server.

        # ls -la /opt/monitoring/os-report/report.py

- Try running the script as zabbix user (if you have the zabbix-agent run as user zabbix)

        root@host# su - zabbix
        zabbix@host$ /opt/monitoring/os-report/report.py os
        zabbix@host$ /opt/monitoring/os-report/report.py package

- Try to get data via zabbix-get

        root@server# zabbix_get -s HOSTIP -k "system.run[/opt/monitoring/os-report/report.py package]"

- Eliminate the influence of SELinux

        # setenforce 0

**Comment by adziubin** [comment]
Permissions set correctly ,

report script returns correct data 

SElinux not instaled (Ubuntu 16.04)

**Comment by samosvat** [comment]
If the command
`zabbix_get -s HOSTIP -k "system.run[/opt/monitoring/os-report/report.py package]"`
returns a list of packages to the console, check the host in Zabbix: do you have this data in host latest data?
<img width="949" alt="image" src="https://user-images.githubusercontent.com/14240138/43515492-50fc8dd8-958b-11e8-8ed5-49baffec3eef.png">


Probably Zabbix hasn't collected the metrics yet. Оn my screenshot you can see that the metric is collected 1 time per day at 13: 24 (you will have a different time):
<img width="762" alt="image" src="https://user-images.githubusercontent.com/14240138/43515293-d077f06c-958a-11e8-8f6b-fd281554dd25.png">

**Comment by adziubin** [comment]
all data comes normally. I'll try to wait until tomorrow and check if zabbix can collect data. Thanks for your work and amazing plugin

**Comment by adziubin** [comment]
All works fine! thanks ! There are several errors with non ASCII encoding, but this is not critical!
