### ISSUE TITLE
user for ack

### ISSUE THREAD

**Issue by alter** [vulnersCom/zabbix-threat-control#18]
Hello,
I'm doing the following command:
`# sudo -i -u zabbix /opt/monitoring/zabbix-threat-control/ztc_fix.py testnet-1 19219 1010665`

And get an error in logs:
Skipping this request to fix.  [ztc_fix.py:90]
2018-09-03 13:10:33,715  11054  INFO  Getting Started with the event: https://zabbix.x/tr_events.php?triggerid=19219&eventid=1010665  [ztc_fix.py:72]
2018-09-03 13:10:33,716  11054  INFO  JSON-RPC Server Endpoint: https://zabbix.x/api_jsonrpc.php  [__init__.py:57]
2018-09-03 13:10:33,720  11054  INFO  Starting new HTTPS connection (1): zabbix.x  [connectionpool.py:761]
2018-09-03 13:10:34,721  11054  INFO  Connected to Zabbix API v.3.4.9  [ztc_fix.py:79]
2018-09-03 13:10:34,736  11054  INFO  ack_user: userX  [ztc_fix.py:88]*
2018-09-03 13:10:34,736  11054  INFO  acknowledge_user: Admin  [ztc_fix.py:89]*
2018-09-03 13:10:34,736  11054  INFO  Not trusted user in acknowledge: userX.
Skipping this request to fix.  [ztc_fix.py:91]

It happens b/c I don't use Admin user, I use LDAP protocol for accessing zabbix with users from ActiveDirectory.

1) Where could I change it?
2) Is it working if several different users can ack events?

* ack_user and acknowledge_user - I've added these variables to output.

**Comment by alter** [comment]
I'm sorry about 1st question, I just did grep 'Admin' in zabbix-threat-control folder and found this variable, but 2nd question is still actual.

**Comment by samosvat** [comment]
Hi!
you can list users separated by commas (in the ztc.conf)

     ### Option: TrustedZabbixUsers
     #   Zabbix users who can initiate the execution of fix-commands.
     #   A list of usernames separated by commas.
     #
     # Mandatory: no
     # Default:
     # TrustedZabbixUser = Admin
     TrustedZabbixUser = FirstLdapUser,SecondLDAPUser

**Comment by alter** [comment]
hm, I don't have such config...

**Comment by samosvat** [comment]
You have an old version! Please update to the latest version of 1.3.4. 
**Just read this issue before updating: https://github.com/vulnersCom/zabbix-threat-control/issues/16**

**Comment by alter** [comment]
I'v setup it using repository http://repo.vulners.com/debian, but ok, let's try with pip:

```pip install -U vulners
Installing collected packages: vulners
Successfully installed vulners-1.3.5

# find / -name 'ztc.conf' -type f
#
```

where should config be?

**Comment by samosvat** [comment]
Install python module:

     pip3 install -U vulners

Install deb-package:

     apt-get update && apt-get install zabbix-threat-control-main

config is here: `/opt/monitoring/zabbix-threat-control/ztc.conf`

**Comment by alter** [comment]
thx, btw, I've found bug in config
```fgrep TrustedZabbixUser ztc.conf
### Option: TrustedZabbixUsers
# TrustedZabbixUser = Admin
```
here is User instead of User**s**
