### ISSUE TITLE
Link template Vulners OS-Report

### ISSUE THREAD

**Issue by sirbusby** [vulnersCom/zabbix-threat-control#2]
When I link the template Vulners OS-Report I get an error.

```
Cannot update host
Details

    Two items ("System information" and "OS - Name") cannot populate one host inventory field "OS", this would lead to a conflict. [hosts.php:598 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CHost->update() → CHost->massUpdate() → CHost->massAdd() → CHostGeneral->massAdd() → CHostGeneral->link() → CItem->syncTemplates() → CItem->inherit() → CItem::validateInventoryLinks() → CApiService::exception() in include/classes/api/services/CItem.php:960]
```

 When I create a new host and first link template Vulners OS-Report, it works. But when I link a template OS Linux, I get an error too.

![screenshot-2018-6-17 zabbix configuration of hosts](https://user-images.githubusercontent.com/35493244/41507765-f0d76dca-7252-11e8-90a0-e955d2099296.png)

**Comment by samosvat** [comment]
Changed the host inventory field for item "OS - Name": os -> os_short.

You'll need to recreate the template "Vulners OS-Report" (if already created).  Оr change inventory field link for item "OS - Name" to "OS (short)" using Zabbix web interface.
