### ISSUE TITLE
Проблема с запуском сканирования

### ISSUE THREAD

**Issue by necroskull** [vulnersCom/zabbix-threat-control#20]
Приветствую, уважаемые разработчики.
OS: FreeBSD FreeBSD 11.2-RELEASE-p2 FreeBSD
Права на файл - -rwxr-xr-x  1 zabbix  zabbix  23054 Sep  6 15:39 scan.py
При запуске от рута - python3 scan.py получаю такую ошибку:

'[root@FreeBSD:zabbix-threat-control]# python3.6 scan.py
INFO:ZTC:Start.
INFO:ZTC:Connected to Zabbix API v.3.4.8
INFO:ZTC:Received from Zabbix 1 hosts for processing
INFO:ZTC:Receiving extended data about hosts from Zabbix
INFO:ZTC:[1 of 1] "Home". Successfully received extended data
INFO:ZTC:Processed hosts: 1.
INFO:ZTC:Checking data from Zabbix'
'--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u041e' in position 55: ordinal not in range(128)
Call stack:
  File "scan.py", line 179, in <module>
    h_matrix[:] = [h for h in h_matrix if os_data_valid(h['OS - Name'], h['OS - Version'], h['OS - Packages'], h['v_name'])]
  File "scan.py", line 179, in <listcomp>
    h_matrix[:] = [h for h in h_matrix if os_data_valid(h['OS - Name'], h['OS - Version'], h['OS - Packages'], h['v_name'])]
  File "scan.py", line 97, in os_data_valid
    logger.info('Excluded {}. \u041eS: {}, Version: {}, Packages: {}'.format(host_name, os, version, len(packages)))
Message: 'Excluded Home. \u041eS: 0, Version: 0, Packages: 1'
Arguments: ()
`

Вы могли бы подсказать путь решения данной проблемы?
Спасибо за внимание.

**Comment by samosvat** [comment]
Привет. 
В файле `scan.py` строка 97:
`logger.info('Excluded {}. ОS: {}, Version: {}, Packages: {}'.format(host_name, os, version, len(packages)))`

Там где `ОS:` - замените символ "О" (кириллическая заглавная О) на латинскую заглавную "O".  Должно заработать.

Ну или [как то так](http://qaru.site/questions/1665407/python-3-unicodeencodeerror-ascii-codec-cant-encode-characters) попробовать поправить - чтобы один раз и навсегда.

**Comment by necroskull** [comment]
Спасибо за ответ! Проблема решена.
