### ISSUE TITLE
Проблема со сканированием хостов

### ISSUE THREAD

**Issue by necroskull** [vulnersCom/zabbix-threat-control#21]
Приветствую, уважаемые разработчики!
после успешной настройки плагина, и запуска файла сканирования на сервере Zabbix, 
[root@FreeBSD:zabbix-threat-control]# python3.6 scan.py
Получаю такой вывод:

INFO:ZTC:Start.
INFO:ZTC:Connected to Zabbix API v.3.4.8
INFO:ZTC:Received from Zabbix 3 hosts for processing
INFO:ZTC:Receiving extended data about hosts from Zabbix
INFO:ZTC:[1 of 3] "Home". Successfully received extended data
INFO:ZTC:[2 of 3] "RaspberryHome". Successfully received extended data
INFO:ZTC:[3 of 3] "Zabbix server". Successfully received extended data
INFO:ZTC:Processed hosts: 3.
INFO:ZTC:Checking data from Zabbix
INFO:ZTC:Excluded Home. OS: 0, Version: 0, Packages: 1
INFO:ZTC:Excluded RaspberryHome. OS: 0, Version: 0, Packages: 1
INFO:ZTC:Excluded Zabbix server. OS: 0, Version: 0, Packages: 1
INFO:ZTC:After checking data from Zabbix, there are 0 entries left. Removed 3
INFO:ZTC:Receiving the vulnerabilities from Vulners
INFO:ZTC:Processed hosts: 0
INFO:ZTC:Exclude invalid response data from Vulners
INFO:ZTC:There are 0 entries left. Removed: 0
INFO:ZTC:There are no data in the host-matrix for further processing. Exit

Может ли это означать неправильную настройку плагина на стороне zabbix-агента?
Я так понимаю, что сканирование, вообще не запустилось?
На каждом из них было проделано следующее:
git clone https://github.com/vulnersCom/zabbix-threat-control.git
mkdir -p /opt/monitoring/
cp -R zabbix-threat-control/os-report /opt/monitoring/
chown -R zabbix:zabbix /opt/monitoring/os-report
и затем
EnableRemoteCommands=1
LogRemoteCommands=1

Спасибо.

**Comment by samosvat** [comment]
Привет. Нужно подождать пока данные с хостов соберутся (их будет видно в Latest Data)
И тогда уже можно вручную запускать сканирование.

Или же подождать того времени, которое было указано при инсталляции. К тому времени все соберется само и скрипты запустятся сами. Останется лишь открыть дашборд.

**Comment by samosvat** [comment]
[По ссылке](https://habr.com/company/vulners/blog/416137/) описана очередность работы:

![](https://habrastorage.org/webt/io/mf/li/iomflipmyk5lxwmn8qbntuswufs.gif)

**Comment by necroskull** [comment]
Спасибо за ответ.

**Comment by samosvat** [comment]
Заработало?
