### ISSUE TITLE
Пустой dashboard

### ISSUE THREAD

**Issue by leksakov** [vulnersCom/zabbix-threat-control#24]
Приветствую, уважаемые разработчики!

При попытке получить инфо хотя бы с самого сервера zabbix, пустой dashboard.
![image](https://user-images.githubusercontent.com/19302062/47365988-667b1f80-d6e5-11e8-873a-db772aa5800c.png)

При ручном запуске scan.py вот такой вывод:
```
INFO:ZTC:Start.
INFO:ZTC:Connected to Zabbix API v.4.0.0
INFO:ZTC:Received from Zabbix 1 hosts for processing
INFO:ZTC:Receiving extended data about hosts from Zabbix
INFO:ZTC:[1 of 1] "Zabbix server". Successfully received extended data
INFO:ZTC:Processed hosts: 1.
INFO:ZTC:Checking data from Zabbix
INFO:ZTC:Excluded Zabbix server. ОS: centos, Version: 7, Packages: 0
INFO:ZTC:After checking data from Zabbix, there are 0 entries left. Removed 1
INFO:ZTC:Receiving the vulnerabilities from Vulners
INFO:ZTC:Processed hosts: 0
INFO:ZTC:Exclude invalid response data from Vulners
INFO:ZTC:There are 0 entries left. Removed: 0
INFO:ZTC:There are no data in the host-matrix for further processing. Exit

```
при запуске ./report.py os & package информацию отображает, но эта информация отсутствует в dashboard.
Тоже самое происходит, если в Vulners OS Report добавить и другие хосты.

**CentOS 7, Zabbix 4.0, Python 3.6.5**

**Comment by samosvat** [comment]
Привет. 
Вижу что на хосте "Zabbix server" нет информации о пакетах. 
Из-за этого span.py исключает этот хост из списка обрабатываемых:

> INFO:ZTC:**_Excluded Zabbix server._** ОS: centos, Version: 7, **_Packages: 0_**
> INFO:ZTC:After checking data from Zabbix, there are **_0 entries left_**. Removed 1

Ну а дальше список из 0 серверов. И само собой 0 результатов.

**Comment by samosvat** [comment]
> при запуске ./report.py os & package информацию отображает, но эта информация отсутствует в dashboard.

Что выдает вот такая команда, запущенная с Zabbix-сервера?
    
    zabbix_get -s HOSTIP -k "system.run[/opt/monitoring/os-report/report.py package]"
Где HOSTIP - IP адрес хоста под названием "Zabbix server"

**Comment by leksakov** [comment]
> > при запуске ./report.py os & package информацию отображает, но эта информация отсутствует в dashboard.
> 
> Что выдает вот такая команда, запущенная с Zabbix-сервера?
> 
> ```
> zabbix_get -s HOSTIP -k "system.run[/opt/monitoring/os-report/report.py package]"
> ```
> Где HOSTIP - IP адрес хоста под названием "Zabbix server"

Выдаёт список пакетов которые установлены на запрашиваемом хосте.

**Comment by samosvat** [comment]
а эти данные есть в последних данных на хосте "Zabbix server" ?
