### ISSUE TITLE
Use built-in item system.sw.packages

### ISSUE THREAD

**Issue by varuzam** [vulnersCom/zabbix-threat-control#3]
Hi
Zabbix has built-in item system.sw.packages which generates list of packages. It would be nice to use it instead of custom scripts

**Comment by samosvat** [comment]
Hi!
This method is suitable for rpm-based distrо:
```
[rpm] GeoIP-1.5.0-11.el7.x86_64, NetworkManager-1.4.0-17.el7_3.x86_64...
```

But for Debian-based Linux does not return the package version:
```
[dpkg] acl, acpi, acpi-support-base, acpid, adduser...
```
While a package version is needed to find the vulnerability!

But thanks for the help - I'll think about how I can use it.

**Comment by varuzam** [comment]
I found the ticket https://support.zabbix.com/browse/ZBXNEXT-2580
It seems nobody is going to fix it. :(

**Comment by samosvat** [comment]
Yes, but I'll try to do a pull-request for this features in https://github.com/zabbix/zabbix/blob/trunk/src/libs/zbxsysinfo/linux/software.c

**Comment by bilkoua** [comment]
Any progress with pull request?

**Comment by samosvat** [comment]
The task is planned. But there are no deadlines.
Probably something will be known in September.

**Comment by bilkoua** [comment]
Any info about pull request?

**Comment by PenelopeFudd** [comment]
Same here; I'm thinking I'll have to create my own for Redhat/Ubuntu: 
```
UserParameter=system.sw.versions,rpm -qa || dpkg-query -W
```
