### ISSUE TITLE
KeyError: 'OPTIONAL'

### ISSUE THREAD

**Issue by ikhudorozhkov** [vulnersCom/zabbix-threat-control#33]
Hi
can anyone pls help me?
when i tried running "/opt/monitoring/zabbix-threat-control/prepare.py -uvtda" to create the objects in Zabbix, i encountered an error saying that KeyError: 'OPTIONAL'.

I am running Zabbix server version 4.2 on CentOS Linux release 7.6
The version of python I'm using is 3.6.

Running "pip3 list" shows:

Package    Version
certifi    2019.3.9
chardet    3.0.4
idna       2.8
jpath      1.6
pip        19.1.1
pyzabbix   0.7.5
requests   2.21.0
setuptools 39.2.0
six        1.12.0
urllib3    1.24.3
vulners    1.5.0

pls help, would really like to get ztc to work with my zabbix server.
Thanks!

Log:

> xorg@ centos ~ $ /opt/monitoring/zabbix-threat-control/scan.py
Traceback (most recent call last):
  File "/opt/monitoring/zabbix-threat-control/scan.py", line 24, in <module>
    from readconfig import *
  File "/opt/monitoring/zabbix-threat-control/readconfig.py", line 18, in <module>
    zbx_verify_ssl = config['OPTIONAL'].getboolean('VerifySSL', True)
  File "/usr/lib64/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'OPTIONAL'

**Comment by ikhudorozhkov** [comment]
thaks to @samosvat .
i crash syntax for config file.
now work fine.

**Comment by arpsyapathy** [comment]
@ikhudorozhkov  @samosvat Hello! I have this error. How to fix? Thank you
