### ISSUE TITLE
cannot install repo

### ISSUE THREAD

**Issue by zshahan** [vulnersCom/zabbix-threat-control#4]
I am trying to follow the readme and install the needed components.  When I attempt to use this url "https://repo.vulners.com/redhat/vulners-repo.rpm", I get a error message stating the ssl certificate expired July 6th.

repo.vulners.com uses an invalid security certificate. The certificate expired on Friday, July 6, 2018, 6:59:59 PM. The current time is July 8, 2018, 8:52 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by vulnersCom** [comment]
Oh, sorry.
Fixed!
