### ISSUE TITLE
Ошибка score ztc.py

### ISSUE THREAD

**Issue by krajster** [vulnersCom/zabbix-threat-control#5]
при обработке  несокльких серверов наблюдается такая ошибка:
WARNING  [4 of 5] Skipping server1.com. Exception: 'score'  [ztc.py:256]
WARNING  [5 of 5] Skipping server2.com. Exception: 'score'  [ztc.py:256]

**Comment by samosvat** [comment]
Привет.  

Вероятно это были проблемы у нас на бэке. Мы пофиксили и сейчас все должно работать штатно. Просто запусти еще раз и проверь.

Если все же не помогло: Мне нужен дамп данных. В нем содержатся все пакеты твоих хостов и ответы вулнерса на эту информацию.

Чтобы его сделать нужно выполнить скрипт с аргументами:

     ./ztc.py --BypassZbxPush --DumpHostMatrix

Полученный файл `/opt/monitoring/zabbix-threat-control/h_matrix_dump` пришли мне в личку.

Чтобы ускорить процесс стукнись в телеграмм @ztcsupport

**Comment by krajster** [comment]
Поддтверждаю, проблема ушла, всё корректно работает. Спасибо.
P.S. если включён на клиенте SELinux=Enforcing  - "report.py package" не отправляет установленные пакеты.

**Comment by samosvat** [comment]
Ну так это же SELinux: ) Нужно для него политику сконфигурировать под это дело..
Вероятно, по мнению selinux, у пользователя zabbix (и в частности у процесса заббикс-агент)  не должно быть полномочий на запуск шелла.

**Comment by krajster** [comment]
Там дело не в shell, а в правах доступа к папке /var/lib/rpm (странно, но
факт).
