### ISSUE TITLE
report.py not found

### ISSUE THREAD

**Issue by drook** [vulnersCom/zabbix-threat-control#6]
I'm getting the 

````zabbix.log
2018-07-12 15:05:00,861  36953  WARNING  Excluded playkey.net - backend2. Exception: could not convert string to float: 'sh: 1: /opt/monitoring/os-report/report.py: not found'  [ztc.py:78]
````

and this clearly indicates that the file is missing on the host that the scan runs on (not the zabbix server), but the most weird thing is that I have it there:

````shell
# ls /opt/monitoring/os-report/report.py
/opt/monitoring/os-report/report.py
````

and I'm stuck. To get rid of any errors I've installed the thread control agent package on all the hosts I'm scanning, - zabbix server and all the hosts of the Vulners group - but I'm still getting the error, but for some reason only on one host (the other is scanning fine).

Could the message be misleading ?

**Comment by samosvat** [comment]
Hi!
- Check that you are using the latest ZTC version (0.3.2)

        grep 'version__ =' /opt/monitoring/zabbix-threat-control/ztc.py

- Check permissions on `/opt/monitoring/os-report/report.py` Zabbix user must be able to run it.

        # ls -la /opt/monitoring/os-report/report.py

- Try running the script as zabbix user (if you have the zabbix-agent run as user zabbix)

        root@host# su - zabbix
        zabbix@host$ /opt/monitoring/os-report/report.py os

- Eliminate the influence of SELinux

        # setenforce 0

**Comment by drook** [comment]
I managed to fix this, but I got strong impression that this plugin somehow caches the previous result, so when I fix something it gets fixed on scan on n+1st pass, not just next. But let's assume it's just me.
