### ISSUE TITLE
"update interval" for items is set to 0

### ISSUE THREAD

**Issue by alter** [vulnersCom/zabbix-threat-control#8]
https://www.zabbix.com/documentation/3.4/manual/config/items/item/custom_intervals
Example:

**0** | 1-7,00:00-7:00 | Item will **NOT** be checked during the night.

I've updated update interval to "1d" and now it works as you meant.

**Comment by samosvat** [comment]
Hi!
To collect at the right time of the day using the functional "[scheduling intervals](https://www.zabbix.com/documentation/3.4/manual/config/items/item/custom_intervals#scheduling_intervals)".
Therefore, the value "update interval"  = 0

But of course you can change the parameters of the collection of metrics as it is convenient for you :)

<img width="541" alt="image" src="https://user-images.githubusercontent.com/14240138/43186559-ad5e0e9c-8ff7-11e8-8d43-485b2ab75099.png">
